######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=false distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
clip front=26.1035 back=-26.4482 frontsurface=26.1035 backsurface=-26.4482 leftsurface=-26.0994 rightsurface=26.4523 leftslopesurface=0 rightslopesurface=0 frontselect=26.1035 backselect=-26.4482 boxoffset=0 objects=all
