######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=false distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
distance 22 52 xoffset=0 yoffset=0
distance 16 21 xoffset=0 yoffset=0
clip front=21.3595 back=-18.7572 frontsurface=21.3595 backsurface=-18.7572 leftsurface=-18.5829 rightsurface=21.5338 leftslopesurface=0 rightslopesurface=0 frontselect=21.3595 backselect=-18.7572 boxoffset=0 objects=all
