######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=false distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
clip front=37.1575 back=-24.5967 frontsurface=37.1575 backsurface=-24.5967 leftsurface=-33.2695 rightsurface=28.4846 leftslopesurface=0 rightslopesurface=0 frontselect=37.1575 backselect=-24.5967 boxoffset=0 objects=all
