######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=false distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
clip front=34.2756 back=-23.5075 frontsurface=34.2756 backsurface=-23.5075 leftsurface=-44.6402 rightsurface=13.1429 leftslopesurface=0 rightslopesurface=0 frontselect=34.2756 backselect=-23.5075 boxoffset=0 objects=all
