######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=false distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
clip front=29.5645 back=-26.4865 frontsurface=29.5645 backsurface=-26.4865 leftsurface=-29.096 rightsurface=26.9551 leftslopesurface=0 rightslopesurface=0 frontselect=29.5645 backselect=-26.4865 boxoffset=0 objects=all
