######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=false distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
clip front=50.0765 back=-10.2223 frontsurface=50.0765 backsurface=-10.2223 leftsurface=-29.5743 rightsurface=30.7244 leftslopesurface=0 rightslopesurface=0 frontselect=50.0765 backselect=-10.2223 boxoffset=0 objects=all
