######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=false distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
clip front=30.9958 back=-25.8391 frontsurface=30.9958 backsurface=-25.8391 leftsurface=-42.3068 rightsurface=14.5282 leftslopesurface=0 rightslopesurface=0 frontselect=30.9958 backselect=-25.8391 boxoffset=0 objects=all
