######################################################
# Please do not edit this file.                      #
# Contents of this file will be overwritten when the #
# project is closed.                                 #
######################################################
ribbon display=ribbonsonly
hbondcriteria display=false distance=2.8 donorangle=120 acceptorangle=90
hbondset1
hbondset2 
hbondset1 
contactcriteria display=false displaygood=false displaybad=true displayugly=true excludehbond=true good=1.3 bad=0.89 ugly=0.75
contactset1
contactset2 
contactset1 
wsassistantcontacthbond intraligandcontacts=false receptorligandcontacts=false
clip front=28.4477 back=-28.9226 frontsurface=28.4477 backsurface=-28.9226 leftsurface=-27.6168 rightsurface=29.7535 leftslopesurface=0 rightslopesurface=0 frontselect=28.4477 backselect=-28.9226 boxoffset=0 objects=all
