#WARNING: This file is automatically overwritten every time you close a project. 
#         Add any startup commands to maestro.cmd
#         ** Do NOT edit this file! **
projectprefer feedbackshow=true
projectprefer feedbackproperty="Title"
projectprefer entryfeedbackshow=true
projectprefer feedbackproperties="s_m_title s_pdb_PDB_ID"
projectprefer phasefeedbackproperties=""
projectprefer entryfeedbackshownames=true
projectprefer jobstatusfeedbackshow=false
projectprefer show2dstructures=false
projectprefer 2dstructureheight=200
projectprefer 2dstructurewidth=300
entryexport selected_properties=""
entryexportspreadsheet selected_properties=""
projectprefer entrylistvisiblesubset=""
projectprefer entrylistcolumnwidths=""
projectprefer showentrylist2dstructures=false
projectprefer entrylist2dstructureheight=75
projectprefer entrylist2dstructurewidth=75
projectprefer showentryliststars=false
projectprefer enotationproperties=""
